
name: CI

on: [ push ]

env:
  CI: true
  node-version: 16

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      name: Node.js ${{ env.node_version }}
      with:
        node-version: ${{ env.node_version }}
    - run: npm install
    - run: npm run lint

  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Node.js ${{ env.node_version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node_version }}
    - run: npm install
    - run: npx -y c8 --reporter=lcovonly npm run test
      env:
        NODE_ENV: cov

    - uses: codecov/codecov-action@v2
    - uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        node-version: [ 14, 16, 18 ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      name: Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run test
